# Generated by Django 4.0.6 on 2022-08-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fathername', models.CharField(max_length=1000)),
                ('classname', models.IntegerField()),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
    ]
